### ISSUE TITLE
teacher-instructions.md is missing

### ISSUE THREAD

**Issue by lurch** [raspberrypilearning/sorting-hat-lesson#2]
As linked to by README.md

**Comment by lurch** [comment]
Now that this resource is using the "new style" (is that publicly documented anywhere yet?) I guess this issue is about the "old style" resource of README.md, and therefore perhaps semi-redundant?

**Comment by bennuttall** [comment]
> is that publicly documented anywhere yet?

Yes. At [raspberrypilearning/make-learn-resource-template](https://github.com/raspberrypilearning/make-learn-resource-template) and [raspberrypilearning/teach-resource-template](https://github.com/raspberrypilearning/teach-resource-template).

Teach resources should have a `lesson-n` folder for each lesson, containing `lesson.md` and optionally `worksheet.md`. `lesson.md` is the lesson plan and `worksheet.md` is the student worksheet (similar to `worksheet.md` in the make and learn resources).

Closing this as there is no `teacher-instructions.md` file needed and no other file is missing.

**Comment by lurch** [comment]
Thanks for the background info Ben.
