### ISSUE TITLE
Instructions for testing mpg123 are wrong

### ISSUE THREAD

**Issue by lurch** [raspberrypilearning/sorting-hat-lesson#3]
In software.md it says:

Test you have the mpg123 installed by entering the following command:
```
sudo python3 -c "import pibrella"
```

**Comment by lurch** [comment]
Also, the ScratchGPIO instructions seem to be incomplete - wget alone will merely download the `isgh6.sh` file, but presumably it needs to be executed too?

**Comment by lurch** [comment]
And the "GET STARTED" button at the bottom of http://www.raspberrypi.org/learning/sorting-hat-lesson/software/ just links to a page with a "NEXT LESSON" button, and clicking on *that* then gives a 404 error.

**Comment by MissPhilbin** [comment]
Both fixed.

**Comment by lurch** [comment]
The ScratchGPIO instructions have been fixed, but software.md still says:

Test you have the `mpg123` installed by entering the following command:
```
sudo python3 -c "import pibrella"
```

**Comment by bennuttall** [comment]
Fixed
